// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/&": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/&" | "/app" | "/auth/login" | "/auth/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  } | {
    id: "ampersand-index";
    page: "/&";
  } | {
    id: "app-index";
    page: "/app";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "ampersand-index": typeof import("./app/routes/_index.tsx");
  "app-index": typeof import("./app/routes/_index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
};